### ISSUE TITLE
Underscores are not being displayed in the terminal when using Firefox

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal#130] opened 2021-09-29 08:24 UTC
**Describe the bug**
When using Firefox, the underscores are not shown in the terminal. (tested in three envs).

**To Reproduce**
1. Open a terminal on Firefox and write an underscore, or check a name file/folder that is supposed to have one.

**Screenshots**
![image](https://user-images.githubusercontent.com/12363250/135231120-92dd35c1-08ae-4d90-8145-3ea402794c81.png)

**Comment by cdanielw** [comment] 2021-09-29 15:21
Which browser are you using? I've been able to reproduce this on Firefox. On Safari and Chrome, underscores do show up for me.

**Comment by dfguerrerom** [comment] 2021-09-29 15:53
I'm using Firefox browser. I've tried on three different machines and the underscores are not shown even when typing them. Currently using Firefox 92.0.1 (64-bit) on a Windows machine.

**Comment by cdanielw** [comment] 2021-10-14 06:41
I believe this is due to a problem with xtermjs:

https://github.com/xtermjs/xterm.js/issues/3353

**Comment by cdanielw** [comment] 2021-11-29 08:48
This has been resolved in a new xterm release.
https://github.com/xtermjs/xterm.js/pull/3370

**Closed by cdanielw** 2021-11-29 08:48 UTC
Labels: bug
